### ISSUE TITLE
How to check the project is running successed?

### ISSUE THREAD

**Issue by fengbuck** [revoltchat/cli#1]

**Comment by fengbuck** [comment]
After "revolt run“，port 9000 9005 has opend , which is web port

**Comment by fengbuck** [comment]
After "revolt run“，port 9000 9050 has opend , which is web port? Has a complete tutorial?

**Comment by insertish** [comment]
`3001` is the web port, as in https://developers.revolt.chat/contributing.
This tool is currently more intended for internal use so I'm not going to be providing any support for it.
